### PR TITLE
Performance and reliability improvements

### PR DESCRIPTION
**Pull request by oliverfoster**
Alternative implementation with updates

Instead of using the jquery onscreen events to calculate the current visible block, this one calculates with a heavily debounced window scroll.

Greatly reduces the calculations required to bookmark properly.

### CODE REVIEW

**Comment by dancgray** [comment]
Getting an issue with notify-shadow class remaining when return in an LMS (tested in SCORM cloud). Tried with develop branch and ABU-1091 notify fix branch.
screen shot 2015-10-26 at 14 30 12

Mac OSX 10.11.1, chrome 47

**Comment by oliverfoster** [comment]
can you enrol me in a course on scorm cloud?

**Comment by oliverfoster** [comment]
which branch did you use? 

i'm currently using develop with a series of accessibility fixes, so i could perhaps narrow it down if i build from scratch.

**Comment by dancgray** [comment]
@oliverfoster, used develop framework branch, bookmarking - hotfix/alternative. Other plugins installed via adapt install, i.e. develop branch.

**Comment by oliverfoster** [comment]
it's a bug with the notify template  pr to fix > adaptlearning/adapt-contrib-vanilla#183

**Comment by moloko** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by himanshu1618** [comment]
+1

**Pull request merged**
