### PR TITLE
update to use 2 spaces for indentation

### PR DESCRIPTION
**Pull request by nilslp**
Bookmarking converted to use 2 spaces for indentation.

### CODE REVIEW

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
did you want to wait for matt's #34 to go in before proceeding with this one?

**Review by cahirodoherty-learningpool — APPROVED** [review]

**Comment by oliverfoster** [comment]
#34 can be merged into here now @nilslp

**Comment by nilslp** [comment]
Haven't been back to this in a while, @oliverfoster happy this can be merged in now?

**Comment by moloko** [comment]
superseded by #37

**Pull request closed without merging**
